package com.project.code.Model;

import org.springframework.data.annotation.Id; 
import org.springframework.data.mongodb.core.mapping.Document;

import jakarta.validation.constraints.NotNull;


// 7. Add @Document annotation:
//    - Use @Document(collection = "reviews") to indicate that this class represents a MongoDB document.
@Document(collection = "reviews") 
public class Review {

// 9. Add @Id annotation:
//    - Use @Id to mark the field 'id' as the primary key for MongoDB.
//    - The 'id' field is of type String and will be automatically generated by MongoDB.
@Id 
private String id; // MongoDB uses String for the ID field
  
// 6. Add validation:
//    - Apply @NotNull to the customerId, productId, storeId, and rating fields to ensure they are not null.
//    - Example: @NotNull(message = "Customer cannot be null")


// 1. Add 'customerId' field:
//    - Type: private Long
//    - This field represents the customer who created the review.
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.
@NotNull(message = "Customer cannot be null") 
private Long customerId; // The customer who created the review

// 2. Add 'productId' field:
//    - Type: private Long
//    - This field represents the product being reviewed.
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.
@NotNull(message = "Product cannot be null") 
private Long productId; // The product being reviewed

// 3. Add 'storeId' field:
//    - Type: private Long
//    - This field represents the store associated with the product.
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.
@NotNull(message = "Store cannot be null") 
private Long storeId; // The store associated with the product


// 4. Add 'rating' field:
//    - Type: private Integer
//    - This field represents the rating given to the product (out of 5).
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.
@NotNull(message = "Rating cannot be null") 
private Integer rating; // Rating out of 5


// 5. Add 'comment' field:
//    - Type: private String
//    - This field represents an optional comment on the product.
private String comment; // Optional comment on the product

// 8. Add constructor:
//    - The constructor should accept values for customerId, productId, storeId, rating, and an optional comment.

// Constructors public Review() { }

public Review(Long customerId, Long productId, Long storeId, Integer rating, String comment) { 
    this.customerId = customerId; 
    this.productId = productId; 
    this.storeId = storeId; 
    this.rating = rating; 
    this.comment = comment;
}


// 10. Add Getters and Setters:
//    - Add getter and setter methods for all fields (customerId, productId, storeId, rating, comment).
  
public String getId() { return id; }

public void setId(String id) { this.id = id; }

public Long getCustomerId() { return customerId; }

public void setCustomerId(Long customerId) { this.customerId = customerId; }

public Long getProductId() { return productId; }

public void setProductId(Long productId) { this.productId = productId; }

public Long getStoreId() { return storeId; }

public void setStoreId(Long storeId) { this.storeId = storeId; }

public Integer getRating() { return rating; }

public void setRating(Integer rating) { this.rating = rating; }

public String getComment() { return comment; }

public void setComment(String comment) { this.comment = comment; }
}
