spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.36.4/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=4dZbWFaQckZlVJuJHmVH7twf
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:TALJuC1ssX2KGr7GHTCWqRMk@172.21.201.34/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

 

