spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.216.18/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=P9ZAUPFmnJVXOrAEpd0NFFZN
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:7CQPYhNqtpA9lgmFT23C2RGQ@172.21.50.126/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

 

